apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: api-gateway
  namespace: fooddelivery
  labels:
    release: kube-prometheus-stack
    app: api-gateway
spec:
  selector:
    matchLabels:
      app: api-gateway
  namespaceSelector:
    matchNames:
      - fooddelivery
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
