apiVersion: apps/v1
kind: Deployment
metadata:
  name: prestashop
  namespace: ecommerce
spec:
  replicas: 2
  selector:
    matchLabels:
      app: prestashop
  template:
    metadata:
      labels:
        app: prestashop
    spec:
      containers:
        - name: prestashop
          image: ghcr.io/nikalexan/sre-final/prestashop:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_SERVER
              value: postgres
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: ecommerce
            - name: DB_USER
              value: prestashop
            - name: DB_PASSWD
              valueFrom:
                secretKeyRef:
                  name: prestashop-secret
                  key: db-password
            - name: PS_FOLDER_ADMIN
              value: admin1
            - name: ADMIN_PASSWD
              valueFrom:
                secretKeyRef:
                  name: prestashop-secret
                  key: prestashop-password
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 120
            periodSeconds: 15
            failureThreshold: 10
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi
