apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: fooddelivery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/nikalexan/food-delivery-project-go/frontend:latest
          ports:
            - containerPort: 3000
          env:
            - name: API_GATEWAY_URL
              value: "http://api-gateway"
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: fooddelivery
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 3000
